/*------------------------------------------------------------------------------
 * Author:              Craig Gibson
 * Project:             Movie Store
 * File name:           ClientStartupGUI
 * Date created:        16/11/2016
 * Operating System:    -Windows 7
 *                      -64 bit OS
 * 
 * Class Description :  This is the home screen GUI when somebody logs into the
 *                      Client Side with all functionality, and options that 
 *                      are available.
 -----------------------------------------------------------------------------*/
package vidstore.projectclient;

import static java.awt.Frame.ICONIFIED;
import static java.awt.Frame.NORMAL;
import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 * This is the Client StartupGUI and this is the home screen for all of the
 * client functions.
 *
 * @author MB2013-0157(Craig Gibson)
 */
public class ClientStartupGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientStartupGUI
     */
    Client cMain;

    /**
     * This is the constructor for the class and sets the default values for
     * when a new Client is run.
     *
     * @param Client cFromMain
     */
    public ClientStartupGUI(Client cFromMain) {
        cMain = cFromMain;
        initComponents();
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(searchButton);
        this.setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
        recDelete.setEnabled(false);
        recInsert.setEnabled(false);
        adLogout.setEnabled(false);
        jMenuItem1.setEnabled(false);
        jMenuItem2.setEnabled(false);
        jMenuItem3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        searchLabel = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        descArea = new javax.swing.JTextArea();
        recDelete = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        recInsert = new javax.swing.JButton();
        refreshSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sMRButton = new javax.swing.JRadioButton();
        sGRButton = new javax.swing.JRadioButton();
        dropDownMBar = new javax.swing.JMenuBar();
        dropMenu = new javax.swing.JMenu();
        adminMenu = new javax.swing.JMenu();
        adLogin = new javax.swing.JMenuItem();
        adLogout = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        help = new javax.swing.JMenuItem();
        exitButton = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Store");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        searchLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchLabel.setText("Enter a movie title:");

        searchBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        movieTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(movieTable);

        descArea.setColumns(20);
        descArea.setRows(5);
        jScrollPane2.setViewportView(descArea);

        recDelete.setText("DELETE");
        recDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recDeleteActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        recInsert.setText("INSERT");
        recInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recInsertActionPerformed(evt);
            }
        });

        refreshSearch.setText("REFRESH SEARCH");
        refreshSearch.setMaximumSize(new java.awt.Dimension(69, 23));
        refreshSearch.setMinimumSize(new java.awt.Dimension(69, 23));
        refreshSearch.setPreferredSize(new java.awt.Dimension(69, 23));
        refreshSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Description:");

        buttonGroup1.add(sMRButton);
        sMRButton.setSelected(true);
        sMRButton.setText("By Movie");

        buttonGroup1.add(sGRButton);
        sGRButton.setText("By Genre");

        dropMenu.setText("File");

        adminMenu.setText("Admin");

        adLogin.setText("Login");
        adLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adLoginActionPerformed(evt);
            }
        });
        adminMenu.add(adLogin);

        adLogout.setText("Logout");
        adLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adLogoutActionPerformed(evt);
            }
        });
        adminMenu.add(adLogout);

        dropMenu.add(adminMenu);

        jMenuItem2.setText("Delete");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        dropMenu.add(jMenuItem2);

        jMenuItem3.setText("Insert");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        dropMenu.add(jMenuItem3);

        jMenuItem1.setText("Refresh Search");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        dropMenu.add(jMenuItem1);

        help.setText("Help Menu");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        dropMenu.add(help);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        dropMenu.add(exitButton);

        dropDownMBar.add(dropMenu);

        setJMenuBar(dropDownMBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addGap(13, 13, 13)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sMRButton)
                            .addComponent(sGRButton))
                        .addGap(26, 26, 26)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sMRButton)
                        .addGap(6, 6, 6)
                        .addComponent(sGRButton)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(recDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(recInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movieTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieTableMouseClicked

        //When a certain cell(movie name) is clicked then the text box
        //will show a description of the movie
        int col = movieTable.getSelectedRow();
        String rw = (String) movieTable.getValueAt(col, 0);
        int sRow = Integer.parseInt(rw);

        //This method assigns a string to the variable and sets the String to 
        //the text displayed
        String dText = cMain.Selection(sRow);
        descArea.setText(dText);
    }//GEN-LAST:event_movieTableMouseClicked

    //Option window on close
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        CloseOperation();
    }//GEN-LAST:event_exitButtonActionPerformed

    //Call the method to search the database for the movie/genre name
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String sch = searchBar.getText();
        boolean movMatch = Pattern.matches("[A-Z][a-z]*\\s*([A-Z][a-z]*\\s*)*",
                sch);
        if (movMatch) {
            if (sch.equals("")) {
                //Do nothing if nothing is entered in the search bar
            } else {
                if (sMRButton.isSelected()) {
                    cMain.search(sch, this, "Movie");
                } else {
                    cMain.search(sch, this, "Genre");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "The name of the "
                    + "movie must start with a capital letter\n"
                    + " and be followed by lowercase letters, the same goes for"
                    + " any following words.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void refreshSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshSearchActionPerformed
        RefreshOperation();
    }//GEN-LAST:event_refreshSearchActionPerformed

    //Option Window on close
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        CloseOperation();
    }//GEN-LAST:event_formWindowClosing

    //Login for Insert and Delete options
    private void adLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adLoginActionPerformed
        cMain.newAdminGUI(this);
    }//GEN-LAST:event_adLoginActionPerformed

    //Logout for Insert and Delete options
    private void adLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adLogoutActionPerformed
        cMain.disableAdmin(this);
    }//GEN-LAST:event_adLogoutActionPerformed

    //Launching the insert GUI
    private void recInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recInsertActionPerformed
        insRec();
    }//GEN-LAST:event_recInsertActionPerformed

    private void recDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recDeleteActionPerformed
        Delete();
    }//GEN-LAST:event_recDeleteActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        Help help = new Help();
        help.setVisible(true);
    }//GEN-LAST:event_helpActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        RefreshOperation();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Delete();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        insRec();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //When this button is selected an Option Menu is opened which 
    // minimises, exits the client window or cancels the quit option.
    /**
     * This is the Close Operation that opens the menu asking the user what
     * he/she would like to do and displays the 3 options.
     *
     */
    public void CloseOperation() {
        String[] Options = new String[]{"Minimise", "Exit", "Cancel"};
        int response = JOptionPane.showOptionDialog(null, "What is it you would"
                + " like to do?", "Exit", 0, JOptionPane.QUESTION_MESSAGE,
                null, Options, null);

        //This operates on which button is selected.
        if (response == 0) {
            this.setState(ICONIFIED);
        } else if (response == 1) {
            System.exit(0);
        } else {
            this.setState(NORMAL);
        }
    }

    public void RefreshOperation() {
        //This is the refresh button, and sends an argument of ??? to the 
        //method which checks what the parameter is and then acts accordingly
        cMain.search("???", this, "");
    }

    public void Delete() {
        //This method deletes the row based on what row is selected using the
        //ID of the row selected
        int sRow = movieTable.getSelectedRow();
        if (sRow == -1) {
            JOptionPane.showMessageDialog(null, "Can't Delete, No row is "
                    + "selected", "Nothing Selected",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String id = (String) movieTable.getValueAt(sRow, 0);
            int sID = Integer.parseInt(id);
            cMain.deleteRec(sID);
        }
    }

    public void insRec() {
        Insert insert = new Insert(cMain);
        insert.setVisible(true);
    }
    /**
     * This is all the main components that are created everytime the system is
     * run.
     *
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem adLogin;
    public javax.swing.JMenuItem adLogout;
    private javax.swing.JMenu adminMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea descArea;
    private javax.swing.JMenuBar dropDownMBar;
    private javax.swing.JMenu dropMenu;
    private javax.swing.JMenuItem exitButton;
    private javax.swing.JMenuItem help;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable movieTable;
    public javax.swing.JButton recDelete;
    public javax.swing.JButton recInsert;
    private javax.swing.JButton refreshSearch;
    private javax.swing.JRadioButton sGRButton;
    private javax.swing.JRadioButton sMRButton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    // End of variables declaration//GEN-END:variables
}
