/*------------------------------------------------------------------------------
 * Author:              Craig Gibson
 * Project:             Movie Store
 * File name:           Insert Class
 * Date created:        16/11/2016
 * Operating System:    -Windows 7
 *                      -64 bit OS
 * 
 * Class Description :  The Insert Class which is a GUI that allows us to insert
 *                      data into the movies table in the database along with
 *                      validating the input in teh frames.
 -----------------------------------------------------------------------------*/
package vidstore.projectclient;

import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author MB2013-0157(Craig Gibson)
 */
public class Insert extends javax.swing.JFrame {

    Client client;

    /**
     * The constructor for the class every time this code is executed.
     *
     * @param Client client
     */
    public Insert(Client client) {
        this.client = client;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        genPane = new javax.swing.JTabbedPane();
        moviePanel = new javax.swing.JPanel();
        movLabel = new javax.swing.JLabel();
        addMov = new javax.swing.JButton();
        movNameTB = new javax.swing.JTextField();
        genIDTB = new javax.swing.JTextField();
        genIDLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTB = new javax.swing.JTextArea();
        desc = new javax.swing.JLabel();
        genrePanel = new javax.swing.JPanel();
        genNameLabel = new javax.swing.JLabel();
        genNameBox = new javax.swing.JTextField();
        addGen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insert");

        movLabel.setText("Movie Name:");

        addMov.setText("Add Movie");
        addMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovActionPerformed(evt);
            }
        });

        genIDLabel.setText("Genre ID:");

        descTB.setColumns(20);
        descTB.setLineWrap(true);
        descTB.setRows(5);
        descTB.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descTB);

        desc.setText("Description:");

        javax.swing.GroupLayout moviePanelLayout = new javax.swing.GroupLayout(moviePanel);
        moviePanel.setLayout(moviePanelLayout);
        moviePanelLayout.setHorizontalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(moviePanelLayout.createSequentialGroup()
                        .addComponent(movLabel)
                        .addGap(18, 18, 18)
                        .addComponent(movNameTB, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(moviePanelLayout.createSequentialGroup()
                        .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(genIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(genIDTB)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        moviePanelLayout.setVerticalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movLabel)
                    .addComponent(movNameTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genIDLabel)
                    .addComponent(genIDTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addGroup(moviePanelLayout.createSequentialGroup()
                        .addComponent(desc)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addMov, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        genPane.addTab("Movie", moviePanel);

        genNameLabel.setText("Genre Name:");

        addGen.setText("Add Genre");
        addGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout genrePanelLayout = new javax.swing.GroupLayout(genrePanel);
        genrePanel.setLayout(genrePanelLayout);
        genrePanelLayout.setHorizontalGroup(
            genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genrePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(genrePanelLayout.createSequentialGroup()
                        .addComponent(genNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(genNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        genrePanelLayout.setVerticalGroup(
            genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genrePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel)
                    .addComponent(genNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(addGen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        genPane.addTab("Genre", genrePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(genPane, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(genPane, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovActionPerformed
        String movName = movNameTB.getText();
        String genID = genIDTB.getText();
        String desc = descTB.getText();
        //This checks the String entered into both text fields so that they
        //start with a capital letter along with any subsequent words.
        boolean movMatch = Pattern.matches("[A-Z][a-z]*\\s*([A-Z][a-z]*\\s*)*", 
                movName);
        boolean genMatch = Pattern.matches("[0-9]+", genID);

        //The following 3 if statements are used for more descriptive errors,
        //on the insert data window. We can't use 1 if statements followed
        //by else if because it will exit after the first if that is true.
        if (desc.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "The Description "
                    + "field may not be left empty, because of future "
                    + "confusion.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (movMatch != true) {
            javax.swing.JOptionPane.showMessageDialog(null, "The name of the "
                    + "movie must start with a capital letter\n"
                    + " and be followed by lowercase letters, the same goes for"
                    + " any following words.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (genMatch != true) {
            javax.swing.JOptionPane.showMessageDialog(null, "The ID of the "
                    + "Genre must be an existing\n genre ID using a combination"
                    + "of the numbers 0-9.", "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }

        //This will only execute if all of the above requirements have been met.
        if (movMatch && genMatch && (!(desc.equals("")))) {
            int genNum = Integer.parseInt(genID);
            client.insertRec(movName, genNum, desc);
            this.setVisible(false);
        }
    }//GEN-LAST:event_addMovActionPerformed
    private void addGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGenActionPerformed
        //This adds a genre name and code to the database to allow for use in
        //the program
        String genreName = genNameBox.getText();
        boolean genMatch = Pattern.matches("[A-Z][a-z]*.([A-Z][a-z]*.)*", 
                genreName);
        client.insertGen(genreName);
    }//GEN-LAST:event_addGenActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGen;
    private javax.swing.JButton addMov;
    private javax.swing.JLabel desc;
    private javax.swing.JTextArea descTB;
    private javax.swing.JLabel genIDLabel;
    private javax.swing.JTextField genIDTB;
    private javax.swing.JTextField genNameBox;
    private javax.swing.JLabel genNameLabel;
    private javax.swing.JTabbedPane genPane;
    private javax.swing.JPanel genrePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel movLabel;
    private javax.swing.JTextField movNameTB;
    private javax.swing.JPanel moviePanel;
    // End of variables declaration//GEN-END:variables
}